# %%
from model.model import LEC
from model.model import LECInfo
from language_data import en_language, nb_language

# %% TV
tv_lec = LEC(
    _id='TV',
    structuringProcess_id='S',
    patternOfVariation_id='g',
    knowledgeBaseRelations=5,
    knowledgeBaseDivision=5,
    spatialScale=0,
)
tv_lec_info_en = LECInfo(
    language_id='en',
    lec=tv_lec,
    name='Duration of period without inundation',
    description='Variation in duration of the period emergent above water vs immersed in water; used to characterise variation across river banks, lake shores, tidal belts and in wetlands; In the littoral belt of lake and sea shores divided into hydro-, geo-, supra- and epilitoral belts, in mires divided into carpets, lawns and hummocks',
)
tv_lec_info_nb = LECInfo(
    language_id='nb',
    lec=tv_lec,
    name='Tørrleggingsvarighet',
    description='''Gradienten fra fullstendig til ingen vanndekning er den viktigste årsaken til variasjon i artssammensetning i den fysiske overgangen mellom vann og land, både langs kysten og langs ferskvannsforekomster, på steder der vannet ikke har så stor bevegelsesenergi at forstyrrelseseffekten overstyrer virkningen av alle andre miljøforhold. Denne gradienten har en direkte parallell i mikrotopografivariasjonen på myr, fra de lavestliggende mykmattene til de høyeste tuetoppene. I NiN versjon 1 ble separate ‘lokale basisøkokliner’ benyttet til å beskrive variasjon relatert til oversvømmings- og tørrleggingsvarighet i fjærebelte/flomsone og i myr. Begge disse kan imidlertid beskrives med samme fysiske variabel (tørrleggingsvarighet), og de tradisjonelle trinninndelingene av dem er helt parallelle (sjøl om ulike begrepsapparater har vært brukt). Derfor blir denne variasjonen beskrevet med en og bare en kompleks miljøvariabel i NiN versjon 2. 
	Varigheten av vanndekning er en viktig faktor i seg sjøl fordi ulike organismer har ulike toleranser og krav i forhold til vannbehov og uttørkingstoleranse. I tillegg virker vannet som forstyrrelsesfaktor (eroderende eller sedimenterende, og gjennom isskuring om vinteren). 
	Strandbeltet eller fjærebeltet omfatter arealet som nedad er avgrenset av laveste normale vannstand og som oppad er avgrenset av høyeste normale vannstand eller som regelmessig blir påvirket av bølgeslag eller sjøsprøyt). Den vertikale utstrekningen av fjærebeltet (TV∙a–g) bestemmes hovedsakelig av tidevannsforskjellen, med unntak for supralitoralbeltets høydeutstrekning (basistrinn TV∙g) som bestemmes av graden av eksponering for vær og vind (tilførsel av havsalt gjennom sjøsprøyt). Den vertikale utstrekningen av flomsonen bestemmes av forhold som påvirker vannføringen i elver og vannstanden i innsjøer (for eksempel vanntilførselen og, i regulerte vannforekomster, reguleringsregimet).
	I motsetning til alle andre trinngrenser, som er klart definert på grunnlag av varigheten av oversvømmelse/tørrlegging, kan strandbeltets øvre grense (dvs. grensa mellom TV∙k og TV∙l) være vanskeligere å definere entydig. På svært eksponerte kyststrekninger står saltspruten til tider langt innover land, og på slike steder finnes derfor saltelskende arter (halofytter) på bergknauser og i klippevegger flere hundre meter innenfor øvre flomål. Grønlie (1948) beskriver dette fra de ytterste øyene på Røst i Lofoten (Nordland). Til tross for at disse øyene har en bredde (langs framherskende vindretning) på inntil 1 km og når 250 m over havet, skriver Grønlie (1948) at det ikke er mulig å finne det vanlige skillet mellom kystberg og innlandsberg på disse øyene fordi også øyenes indre deler er eksponert for betydelig sjøsprøyt (’washing by sea’) og hele vegetasjonen derfor får innslag av halofile arter. Idéen om to belter over normalt flomål, ’supralitoralbeltet’ som tilføres havvann i form av direkte sjøsprøyt (TV∙ijk) og ’epilitoralbeltet’ (TV∙l) som tilføres havsalt i form av aerosoler, går i hvert fall tilbake til Sernander (1917). Du Rietz (1932) bruker begrepene ’hygrohalofytt’ og ’aerohalofytt’ om planter som kan leve henholdsvis i supralitoralbeltet og epilitoralbeltet. Supra- og epilitoralbeltene øker i horisontal og vertikal utstrekning med økende grad av eksponering for vær og vind. På de mest eksponerte stedene består kysten av nakent fjell, og det er derfor først og fremst på nakent bergsubstrat at det er vanskelig å trekke en klar øvre grense for fjærebeltet. På steder som er mindre sterkt eksponert finnes oftest ei skarp grense mellom de to beltene fordi den direkte påvirkningen fra saltvann er direkte utslagsgivende for landplanters nedre grenser mot stranda. Et typisk trekk, som kan gi grunnlag for operasjonell grensetrekking mellom strandbeltet og ‘land’ er at lyngarter som for eksempel krekling (Empetrum nigrum) og røsslyng (Calluna vulgaris) alltid mangler i supralitoralbeltet.
	Med vekslende intervaller forekommer sjøsaltepisoder; det vil si spesielle vær- og vindforhold som medfører transport av sjøsalt langt (i ekstreme tilfeller inntil 10–15 km) innover land. Sjøsaltepisoder kan ta livet av eller sterkt redusere vitaliteten til landlevende arter med lav salttoleranse, som for eksempel furu og krekling. Fordi sjøsaltepisoder finner sted så sporadisk (og de biologiske effektene er til dels dårlig dokumentert), er det vanskelig å avgrense epilitoralbeltet (som sporadisk utsettes for sjøsaltepisoder) fra landsystemene innenfor, som aldri utsettes for saltpåvirkning, ikke engang i form av aerosoler (TV∙+).
	‘Mykmatte–tue-gradienten’ er en av de 'klassiske gradientene' i fennoskandisk myrvegetasjonsøkologi. I tillegg til å uttrykke oversvømmelsesvarighet, som er viktig som miljøstress- (og i noen grad også som forstyrrelsesvariabel) i myr, kjennetegnes også trinnene TV∙c–j i myr ved karakteristiske torvegenskaper (pH, redokspotensiale, torvfasthet etc.). Karplanteartenes fordeling langs denne komplekse miljøvariabelen på myr begrenses nedad først og fremst av toleranse for oversvømmelse. Arter som lever i fast- og mykmatter har tilpasninger til å tåle oksygenmangel i rotsjiktet (f.eks. gjennomluftingsvev i røttene).
	Parallelliteten mellom de tørrleggingsvarighet i flomsonen og på myr illustreres av at mange myk- og fastmattearter, f.eks. dikesoldogg (Drosera intermedia) og stivtorvmose (Sphagnum compactum), også forekommer i midtre/øvre landstrand på innsjøstrender. Det er betydelig variasjon i forstyrrelsesintensitet langs tørrleggingsvarighet (TV); først og fremst på grunn av iserosjon men også på grunn av vannerosjon (bølgevirkning). Forstyrrelse er sannsynligvis en viktigere faktor langs innsjøstrender enn på torvmark.
'''
)