// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQY5pTaO94H6pKCMpHEbZiBSulfp_-IY',
    appId: '1:47102161738:web:0e636d33fc58f8e32547b3',
    messagingSenderId: '47102161738',
    projectId: 'natur-i-norge-guide',
    authDomain: 'natur-i-norge-guide.firebaseapp.com',
    storageBucket: 'natur-i-norge-guide.firebasestorage.app',
    measurementId: 'G-MTGM733RFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDncGW0FOzZY22pmVMyhxxse9ZlRHorHW4',
    appId: '1:47102161738:android:3d1ff49c80f6fd922547b3',
    messagingSenderId: '47102161738',
    projectId: 'natur-i-norge-guide',
    storageBucket: 'natur-i-norge-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSDas9NUblC_qCjhpcVwRJlw2K91seeM',
    appId: '1:47102161738:ios:032bcb9096706f712547b3',
    messagingSenderId: '47102161738',
    projectId: 'natur-i-norge-guide',
    storageBucket: 'natur-i-norge-guide.firebasestorage.app',
    iosClientId: '47102161738-6jc5ecc3qgdj9e62csmrm1e14d3s8o3i.apps.googleusercontent.com',
    iosBundleId: 'no.naturinorge.naturinorgeGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSDas9NUblC_qCjhpcVwRJlw2K91seeM',
    appId: '1:47102161738:ios:e56af58c5483c9722547b3',
    messagingSenderId: '47102161738',
    projectId: 'natur-i-norge-guide',
    storageBucket: 'natur-i-norge-guide.firebasestorage.app',
    iosClientId: '47102161738-r97vaii807j0jlhps7t2sb7p9pb6d4v1.apps.googleusercontent.com',
    iosBundleId: 'com.michaltorma.ninGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQY5pTaO94H6pKCMpHEbZiBSulfp_-IY',
    appId: '1:47102161738:web:861ab8107079ae7c2547b3',
    messagingSenderId: '47102161738',
    projectId: 'natur-i-norge-guide',
    authDomain: 'natur-i-norge-guide.firebaseapp.com',
    storageBucket: 'natur-i-norge-guide.firebasestorage.app',
    measurementId: 'G-VEXV0LBLWL',
  );

}