# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to TestFlight"
  lane :deploy do
    # Build the IPA using Flutter (respects NiN 3.0 and excludes dev_dependencies)
    sh "cd ../.. && flutter build ipa --release"
    
    # Upload to TestFlight
    upload_to_testflight(
      ipa: "../build/ios/ipa/naturinorge_guide.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
