from .f.f1_major_type import f1_major_type
from .f.f2_major_type import f2_major_type
from .f.f3_major_type import f3_major_type
from .f.f4_major_type import f4_major_type
from .f.f5_major_type import f5_major_type
from .h.h1_major_type import h1_major_type
from .h.h2_major_type import h2_major_type
from .h.h3_major_type import h3_major_type
from .h.h4_major_type import h4_major_type
from .i.i1_major_type import i1_major_type
from .i.i2_major_type import i2_major_type
from .l.l1_major_type import l1_major_type
from .l.l2_major_type import l2_major_type
from .l.l3_major_type import l3_major_type
from .l.l4_major_type import l4_major_type
from .l.l5_major_type import l5_major_type
from .l.l6_major_type import l6_major_type
from .l.l7_major_type import l7_major_type
from .l.l8_major_type import l8_major_type
from .m.m10_major_type import m10_major_type
from .m.m11_major_type import m11_major_type
from .m.m12_major_type import m12_major_type
from .m.m13_major_type import m13_major_type
from .m.m14_major_type import m14_major_type
from .m.m15_major_type import m15_major_type
from .m.m1_major_type import m1_major_type
from .m.m2_major_type import m2_major_type
from .m.m3_major_type import m3_major_type
from .m.m4_major_type import m4_major_type
from .m.m5_major_type import m5_major_type
from .m.m6_major_type import m6_major_type
from .m.m7_major_type import m7_major_type
from .m.m8_major_type import m8_major_type
from .m.m9_major_type import m9_major_type
from .t.t10_major_type import t10_major_type
from .t.t11_major_type import t11_major_type
from .t.t12_major_type import t12_major_type
from .t.t13_major_type import t13_major_type
from .t.t14_major_type import t14_major_type
from .t.t15_major_type import t15_major_type
from .t.t16_major_type import t16_major_type
from .t.t17_major_type import t17_major_type
from .t.t18_major_type import t18_major_type
from .t.t19_major_type import t19_major_type
from .t.t1_major_type import t1_major_type
from .t.t20_major_type import t20_major_type
from .t.t21_major_type import t21_major_type
from .t.t22_major_type import t22_major_type
from .t.t23_major_type import t23_major_type
from .t.t24_major_type import t24_major_type
from .t.t25_major_type import t25_major_type
from .t.t26_major_type import t26_major_type
from .t.t27_major_type import t27_major_type
from .t.t28_major_type import t28_major_type
from .t.t29_major_type import t29_major_type
from .t.t2_major_type import t2_major_type
from .t.t30_major_type import t30_major_type
from .t.t31_major_type import t31_major_type
from .t.t32_major_type import t32_major_type
from .t.t33_major_type import t33_major_type
from .t.t34_major_type import t34_major_type
from .t.t35_major_type import t35_major_type
from .t.t36_major_type import t36_major_type
from .t.t37_major_type import t37_major_type
from .t.t38_major_type import t38_major_type
from .t.t39_major_type import t39_major_type
from .t.t3_major_type import t3_major_type
from .t.t40_major_type import t40_major_type
from .t.t41_major_type import t41_major_type
from .t.t42_major_type import t42_major_type
from .t.t43_major_type import t43_major_type
from .t.t44_major_type import t44_major_type
from .t.t45_major_type import t45_major_type
from .t.t4_major_type import t4_major_type
from .t.t5_major_type import t5_major_type
from .t.t6_major_type import t6_major_type
from .t.t7_major_type import t7_major_type
from .t.t8_major_type import t8_major_type
from .t.t9_major_type import t9_major_type
from .v.v10_major_type import v10_major_type
from .v.v11_major_type import v11_major_type
from .v.v12_major_type import v12_major_type
from .v.v13_major_type import v13_major_type
from .v.v1_major_type import v1_major_type
from .v.v2_major_type import v2_major_type
from .v.v3_major_type import v3_major_type
from .v.v4_major_type import v4_major_type
from .v.v5_major_type import v5_major_type
from .v.v6_major_type import v6_major_type
from .v.v7_major_type import v7_major_type
from .v.v8_major_type import v8_major_type
from .v.v9_major_type import v9_major_type

major_type_list = [f1_major_type, f2_major_type, f3_major_type, f4_major_type, f5_major_type, h1_major_type, h2_major_type, h3_major_type, h4_major_type, i1_major_type, i2_major_type, l1_major_type, l2_major_type, l3_major_type, l4_major_type, l5_major_type, l6_major_type, l7_major_type, l8_major_type, m10_major_type, m11_major_type, m12_major_type, m13_major_type, m14_major_type, m15_major_type, m1_major_type, m2_major_type, m3_major_type, m4_major_type, m5_major_type, m6_major_type, m7_major_type, m8_major_type, m9_major_type, t10_major_type, t11_major_type, t12_major_type, t13_major_type, t14_major_type, t15_major_type, t16_major_type, t17_major_type, t18_major_type, t19_major_type, t1_major_type, t20_major_type,
                   t21_major_type, t22_major_type, t23_major_type, t24_major_type, t25_major_type, t26_major_type, t27_major_type, t28_major_type, t29_major_type, t2_major_type, t30_major_type, t31_major_type, t32_major_type, t33_major_type, t34_major_type, t35_major_type, t36_major_type, t37_major_type, t38_major_type, t39_major_type, t3_major_type, t40_major_type, t41_major_type, t42_major_type, t43_major_type, t44_major_type, t45_major_type, t4_major_type, t5_major_type, t6_major_type, t7_major_type, t8_major_type, t9_major_type, v10_major_type, v11_major_type, v12_major_type, v13_major_type, v1_major_type, v2_major_type, v3_major_type, v4_major_type, v5_major_type, v6_major_type, v7_major_type, v8_major_type, v9_major_type]


def saveMajorTypes(session):
    for major_type in major_type_list:
        session.add(major_type)
    session.commit()
