#%%
from database_fill.language_data import en_language, nb_language
from database_fill.major_type_group_data import m_major_type_group
from database_fill.major_type_group_data import l_major_type_group
from database_fill.major_type_group_data import t_major_type_group
from database_fill.major_type_group_data import v_major_type_group
from database_fill.major_type_group_data import h_major_type_group
from database_fill.major_type_group_data import f_major_type_group
from database_fill.major_type_group_data import s_major_type_group

# %% 